[package]
name = "deja-dup-auto-ignore"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
ignore = "0.4"
shellexpand = "3.1"
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3.13"
